Repository openshift/loki, pull requests merged in 2022-11, with the labels that each got.

#68 Update from upstream repository
  operator/.bingo/Variables.mk
  operator/.bingo/gen-crd-api-reference-docs.mod
  operator/.bingo/gen-crd-api-reference-docs.sum
  operator/.bingo/hugo.mod
  operator/.bingo/variables.env
  operator/CHANGELOG.md
  operator/Makefile
  operator/apis/config/v1/doc.go
  operator/apis/loki/register.go
  operator/apis/loki/v1/doc.go
  operator/apis/loki/v1/groupversion_info.go
  operator/apis/loki/v1/lokistack_types.go
  operator/apis/loki/v1beta1/doc.go
  operator/apis/loki/v1beta1/groupversion_info.go
  operator/config/docs/config.json
  operator/config/docs/templates/members.tpl
  operator/config/docs/templates/pkg.tpl
  operator/config/docs/templates/type.tpl
  operator/docs/operator/api.md
  operator/docs/operator/feature-gates.md
  operator/internal/manifests/querier.go
  operator/internal/manifests/ruler.go
  operator/internal/manifests/service_test.go
  operator/website/config.toml
Labels: approved

#67 [release-5.5] LOG-3251: Add valid subscription annotation to metadata
  operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
  operator/config/manifests/bases/loki-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#69 Update from upstream repository
  CHANGELOG.md
  clients/pkg/logentry/stages/decolorize.go
  clients/pkg/logentry/stages/decolorize_test.go
  clients/pkg/logentry/stages/stage.go
  clients/pkg/promtail/targets/windows/format.go
  clients/pkg/promtail/targets/windows/target_test.go
  docs/sources/clients/promtail/stages/_index.md
  docs/sources/clients/promtail/stages/cri.md
  docs/sources/clients/promtail/stages/decolorize.md
  docs/sources/installation/helm/install-scalable/index.md
  docs/sources/installation/helm/reference.md
  docs/sources/logql/log_queries.md
  docs/sources/logql/query_examples.md
  docs/sources/operations/troubleshooting.md
  go.mod
  go.sum
  operator/Makefile
  pkg/distributor/ratestore.go
  pkg/distributor/ratestore_test.go
  pkg/logql/log/fmt.go
  pkg/logql/log/fmt_test.go
  pkg/logql/syntax/ast.go
  pkg/logql/syntax/expr.y
  pkg/logql/syntax/expr.y.go
  pkg/logql/syntax/lex.go
  pkg/logql/syntax/lex_test.go
  pkg/logql/syntax/parser_test.go
  pkg/storage/chunk/cache/fifo_cache.go
  pkg/storage/stores/indexshipper/downloads/index_set.go
  pkg/storage/stores/series/index/caching_index_client.go
  production/helm/loki/CHANGELOG.md
  production/helm/loki/Chart.yaml
  production/helm/loki/README.md
  production/helm/loki/templates/single-binary/pdb.yaml
  production/helm/loki/values.yaml
  production/ksonnet/loki-simple-scalable/example/README.md
  production/ksonnet/loki-simple-scalable/example/main.jsonnet
  vendor/github.com/sony/gobreaker/.travis.yml
  vendor/github.com/sony/gobreaker/README.md
  vendor/github.com/sony/gobreaker/gobreaker.go
  vendor/modules.txt
Labels: approved

#74 Update from upstream repository
  CHANGELOG.md
  docs/sources/installation/helm/install-scalable/index.md
  docs/sources/installation/helm/reference.md
  docs/sources/release-notes/_index.md
  docs/sources/release-notes/v2-7.md
  docs/sources/upgrading/_index.md
  operator/apis/config/v1/projectconfig_types.go
  operator/apis/loki/v1/lokistack_types.go
  operator/apis/loki/v1/zz_generated.deepcopy.go
  operator/bundle/manifests/loki-operator-manager-config_v1_configmap.yaml
  operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/manifests/loki.grafana.com_lokistacks.yaml
  operator/config/crd/bases/loki.grafana.com_lokistacks.yaml
  operator/config/manifests/bases/loki-operator.clusterserviceversion.yaml
  operator/config/overlays/openshift/controller_manager_config.yaml
  operator/config/rbac/role.yaml
  operator/controllers/loki/lokistack_controller.go
  operator/controllers/loki/lokistack_controller_test.go
  operator/docs/operator/feature-gates.md
  operator/go.mod
  operator/go.sum
  operator/internal/manifests/compactor.go
  operator/internal/manifests/indexgateway.go
  operator/internal/manifests/ingester.go
  operator/internal/manifests/querier.go
  operator/internal/manifests/var.go
  production/helm/loki/Chart.yaml
  production/helm/loki/README.md
  production/helm/loki/values.yaml
Labels: approved

#75 Update from upstream repository
  CHANGELOG.md
  docs/sources/configuration/_index.md
  operator/CHANGELOG.md
  operator/README.md
  operator/apis/loki/v1/lokistack_types.go
  operator/bundle/manifests/loki.grafana.com_lokistacks.yaml
  operator/config/crd/bases/loki.grafana.com_lokistacks.yaml
Labels: approved

#76 [release 5.5] Backport PR grafana/7711
  operator/CHANGELOG.md
  operator/apis/loki/v1/lokistack_types.go
  operator/bundle/manifests/loki.grafana.com_lokistacks.yaml
  operator/config/crd/bases/loki.grafana.com_lokistacks.yaml
Labels: lgtm, approved

#77 Update from upstream repository
  docs/sources/release-notes/v2-7.md
  operator/.bingo/Variables.mk
  operator/.bingo/gen-crd-api-reference-docs.mod
  operator/.bingo/gen-crd-api-reference-docs.sum
  operator/.bingo/variables.env
  operator/CHANGELOG.md
  operator/apis/loki/v1/lokistack_types.go
  operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/manifests/loki.grafana.com_lokistacks.yaml
  operator/config/crd/bases/loki.grafana.com_lokistacks.yaml
  operator/config/manifests/bases/loki-operator.clusterserviceversion.yaml
  operator/config/rbac/role.yaml
  operator/controllers/loki/lokistack_controller.go
  operator/controllers/loki/lokistack_controller_test.go
  operator/docs/operator/api.md
  operator/docs/operator/feature-gates.md
  operator/go.mod
  operator/go.sum
  operator/internal/external/k8s/builder.go
  operator/internal/external/k8s/k8sfakes/fake_builder.go
  operator/internal/handlers/internal/openshift/proxy.go
  operator/internal/handlers/internal/openshift/proxy_test.go
  operator/internal/handlers/lokistack_create_or_update.go
  operator/internal/manifests/compactor.go
  operator/internal/manifests/distributor.go
  operator/internal/manifests/indexgateway.go
  operator/internal/manifests/ingester.go
  operator/internal/manifests/proxy_env.go
  operator/internal/manifests/proxy_env_test.go
  operator/internal/manifests/querier.go
  operator/internal/manifests/query-frontend.go
  operator/internal/manifests/ruler.go
  operator/internal/manifests/var.go
Labels: approved

#79 [release-5.5] Backport PR grafana/loki#7744
  operator/CHANGELOG.md
  operator/apis/loki/v1/lokistack_types.go
  operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
  operator/config/manifests/bases/loki-operator.clusterserviceversion.yaml
Labels: approved

#80 [release-5.5] Fix changelog entries
  operator/CHANGELOG.md
Labels: lgtm, approved

#81 Update from upstream repository
  CHANGELOG.md
  examples/getting-started/docker-compose.yaml
  flake.nix
  integration/cluster/cluster.go
  integration/loki_micro_services_delete_test.go
  nix/README.md
  nix/build-vars.nix
  nix/default.nix
  nix/generate-build-vars.sh
  nix/loki.nix
  operator/internal/manifests/build_test.go
  operator/internal/manifests/compactor.go
  operator/internal/manifests/config.go
  operator/internal/manifests/distributor.go
  operator/internal/manifests/indexgateway.go
  operator/internal/manifests/ingester.go
  operator/internal/manifests/internal/config/build_test.go
  operator/internal/manifests/internal/config/loki-config.yaml
  operator/internal/manifests/internal/config/options.go
  operator/internal/manifests/querier.go
  operator/internal/manifests/query-frontend.go
  operator/internal/manifests/ruler.go
  operator/internal/manifests/service.go
  operator/internal/manifests/service_test.go
  production/helm/loki/CHANGELOG.md
  production/helm/loki/Chart.yaml
  production/helm/loki/README.md
  production/helm/loki/templates/single-binary/statefulset.yaml
  production/loki-mixin-compiled-ssd/dashboards/loki-operational.json
  production/loki-mixin-compiled/dashboards/loki-operational.json
  production/loki-mixin/dashboards/dashboard-loki-operational.json
Labels: approved

#84 Update from upstream repository
  operator/CHANGELOG.md
  operator/internal/manifests/internal/alerts/prometheus-alerts.yaml
Labels: approved

#87 [release-v2.7.0-pre] Backport grafana/release-2.7.x#7607
  pkg/loki/loki.go
  pkg/storage/stores/indexshipper/compactor/compactor_client.go
Labels: lgtm

#85 Update from upstream repository
  CHANGELOG.md
  clients/pkg/promtail/targets/cloudflare/fields.go
  clients/pkg/promtail/targets/cloudflare/target.go
  clients/pkg/promtail/targets/docker/target.go
  clients/pkg/promtail/targets/lokipush/pushtargetmanager_test.go
  cmd/loki-canary/main.go
  docs/sources/configuration/_index.md
  docs/sources/installation/helm/reference.md
  integration/loki_micro_services_delete_test.go
  operator/internal/manifests/internal/alerts/testdata/test.yaml
  pkg/canary/writer/push.go
  pkg/canary/writer/push_test.go
  pkg/logql/syntax/lex.go
  pkg/logqlmodel/logqlmodel.go
  pkg/logqlmodel/metadata/context_test.go
  pkg/loki/common/common.go
  pkg/loki/loki.go
  pkg/loki/modules.go
  pkg/querier/queryrange/queryrangebase/middleware_test.go
  pkg/querier/queryrange/queryrangebase/results_cache.go
  pkg/querier/queryrange/queryrangebase/results_cache_test.go
  pkg/querier/worker_service.go
  pkg/storage/stores/indexshipper/compactor/client/grpc.go
  pkg/storage/stores/indexshipper/compactor/client/grpc/grpc.pb.go
  pkg/storage/stores/indexshipper/compactor/client/grpc/grpc.proto
  pkg/storage/stores/indexshipper/compactor/client/http.go
  pkg/storage/stores/indexshipper/compactor/compactor.go
  pkg/storage/stores/indexshipper/compactor/compactor_client.go
  pkg/storage/stores/indexshipper/compactor/deletion/delete_request.go
  pkg/storage/stores/indexshipper/compactor/deletion/delete_requests_client.go
  pkg/storage/stores/indexshipper/compactor/deletion/delete_requests_client_test.go
  pkg/storage/stores/indexshipper/compactor/deletion/delete_requests_manager_test.go
  pkg/storage/stores/indexshipper/compactor/deletion/grpc_request_handler.go
  pkg/storage/stores/indexshipper/compactor/deletion/grpc_request_handler_test.go
  pkg/storage/stores/indexshipper/compactor/deletion/metrics.go
  pkg/storage/stores/indexshipper/compactor/generationnumber/gennumber_client.go
  pkg/storage/stores/indexshipper/compactor/generationnumber/gennumber_client_test.go
  pkg/storage/stores/indexshipper/compactor/generationnumber/gennumber_loader.go
  pkg/storage/stores/indexshipper/compactor/generationnumber/gennumber_loader_test.go
  pkg/util/marshal/marshal.go
  production/helm/loki/CHANGELOG.md
  production/helm/loki/Chart.yaml
  production/helm/loki/README.md
  production/helm/loki/templates/_helpers.tpl
  production/helm/loki/templates/provisioner/job-provisioner.yaml
  production/helm/loki/templates/serviceaccount.yaml
  production/helm/loki/templates/tokengen/job-tokengen.yaml
  production/helm/loki/values.yaml
Labels: approved

#89 [release-5.6] Update from upstream/main repository
  CHANGELOG.md
  clients/pkg/promtail/targets/cloudflare/fields.go
  clients/pkg/promtail/targets/lokipush/pushtargetmanager_test.go
  docs/sources/configuration/_index.md
  docs/sources/installation/helm/reference.md
  integration/loki_micro_services_delete_test.go
  operator/CHANGELOG.md
  operator/internal/manifests/internal/config/build_test.go
  operator/internal/manifests/internal/config/loki-config.yaml
  pkg/logql/syntax/lex.go
  pkg/logqlmodel/logqlmodel.go
  pkg/logqlmodel/metadata/context_test.go
  pkg/loki/common/common.go
  pkg/loki/loki.go
  pkg/loki/modules.go
  pkg/querier/queryrange/queryrangebase/middleware_test.go
  pkg/querier/queryrange/queryrangebase/results_cache.go
  pkg/querier/queryrange/queryrangebase/results_cache_test.go
  pkg/storage/stores/indexshipper/compactor/client/grpc.go
  pkg/storage/stores/indexshipper/compactor/client/grpc/grpc.pb.go
  pkg/storage/stores/indexshipper/compactor/client/grpc/grpc.proto
  pkg/storage/stores/indexshipper/compactor/client/http.go
  pkg/storage/stores/indexshipper/compactor/compactor.go
  pkg/storage/stores/indexshipper/compactor/compactor_client.go
  pkg/storage/stores/indexshipper/compactor/deletion/delete_request.go
  pkg/storage/stores/indexshipper/compactor/deletion/delete_requests_client.go
  pkg/storage/stores/indexshipper/compactor/deletion/delete_requests_client_test.go
  pkg/storage/stores/indexshipper/compactor/deletion/delete_requests_manager_test.go
  pkg/storage/stores/indexshipper/compactor/deletion/grpc_request_handler.go
  pkg/storage/stores/indexshipper/compactor/deletion/grpc_request_handler_test.go
  pkg/storage/stores/indexshipper/compactor/deletion/metrics.go
  pkg/storage/stores/indexshipper/compactor/generationnumber/gennumber_client.go
  pkg/storage/stores/indexshipper/compactor/generationnumber/gennumber_client_test.go
  pkg/storage/stores/indexshipper/compactor/generationnumber/gennumber_loader.go
  pkg/storage/stores/indexshipper/compactor/generationnumber/gennumber_loader_test.go
  pkg/util/marshal/marshal.go
  production/helm/loki/CHANGELOG.md
  production/helm/loki/Chart.yaml
  production/helm/loki/README.md
  production/helm/loki/templates/_helpers.tpl
  production/helm/loki/templates/provisioner/job-provisioner.yaml
  production/helm/loki/templates/serviceaccount.yaml
  production/helm/loki/templates/tokengen/job-tokengen.yaml
  production/helm/loki/values.yaml
Labels: lgtm, approved

#88 Update from upstream repository
  operator/CHANGELOG.md
  operator/internal/manifests/internal/config/build_test.go
  operator/internal/manifests/internal/config/loki-config.yaml
Labels: lgtm, approved
