Repository openshift/loki, pull requests merged in 2023-05, with the labels that each got.

#130 LOG-4041: Update skipRange to allow updating from 5.5 onwards
  operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
  operator/config/manifests/openshift/bases/loki-operator.clusterserviceversion.yaml
Labels: lgtm, approved, jira/valid-reference

#133 [release-5.7] Backport PR grafana/loki#9433
  operator/internal/manifests/compactor_test.go
  operator/internal/manifests/config_test.go
  operator/internal/manifests/distributor_test.go
  operator/internal/manifests/indexgateway_test.go
  operator/internal/manifests/ingester_test.go
  operator/internal/manifests/mutate_test.go
  operator/internal/manifests/querier_test.go
  operator/internal/manifests/ruler_test.go
  operator/internal/manifests/rules_config_test.go
Labels: lgtm, approved

#134 [release-5.6] Backport PR grafana/loki#9433
  operator/internal/manifests/compactor_test.go
  operator/internal/manifests/config_test.go
  operator/internal/manifests/distributor_test.go
  operator/internal/manifests/indexgateway_test.go
  operator/internal/manifests/ingester_test.go
  operator/internal/manifests/mutate_test.go
  operator/internal/manifests/querier_test.go
  operator/internal/manifests/ruler_test.go
  operator/internal/manifests/rules_config_test.go
Labels: lgtm, approved

#135 [release-5.5] Backport PR grafana/loki#9433
  operator/internal/manifests/compactor_test.go
  operator/internal/manifests/config_test.go
  operator/internal/manifests/distributor_test.go
  operator/internal/manifests/indexgateway_test.go
  operator/internal/manifests/ingester_test.go
  operator/internal/manifests/mutate_test.go
  operator/internal/manifests/querier_test.go
  operator/internal/manifests/ruler_test.go
  operator/internal/manifests/rules_config_test.go
Labels: lgtm, approved

#140 [release-5.7] Backport PR grafana/loki#9346
  operator/CHANGELOG.md
  operator/apis/config/v1/projectconfig_types.go
  operator/bundle/community-openshift/manifests/loki-operator-manager-config_v1_configmap.yaml
  operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/openshift/manifests/loki-operator-manager-config_v1_configmap.yaml
  operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
  operator/config/manifests/community-openshift/bases/loki-operator.clusterserviceversion.yaml
  operator/config/overlays/community-openshift/controller_manager_config.yaml
  operator/config/overlays/openshift/controller_manager_config.yaml
  operator/controllers/loki/lokistack_controller.go
  operator/controllers/loki/lokistack_controller_test.go
  operator/docs/operator/api.md
  operator/docs/operator/feature-gates.md
  operator/internal/manifests/gateway_tenants.go
  operator/internal/manifests/gateway_tenants_test.go
  operator/internal/manifests/gateway_test.go
  operator/internal/manifests/openshift/build.go
  operator/internal/manifests/openshift/build_test.go
  operator/internal/manifests/openshift/options.go
  operator/main.go
Labels: approved

#142 [release-5.6] Backport PR grafana/loki#9346
  operator/CHANGELOG.md
  operator/apis/config/v1/projectconfig_types.go
  operator/bundle/manifests/loki-operator-manager-config_v1_configmap.yaml
  operator/config/overlays/openshift/controller_manager_config.yaml
  operator/controllers/loki/lokistack_controller.go
  operator/controllers/loki/lokistack_controller_test.go
  operator/docs/operator/api.md
  operator/docs/operator/feature-gates.md
  operator/internal/manifests/gateway_tenants.go
  operator/internal/manifests/gateway_tenants_test.go
  operator/internal/manifests/gateway_test.go
  operator/internal/manifests/openshift/build.go
  operator/internal/manifests/openshift/build_test.go
  operator/internal/manifests/openshift/options.go
  operator/main.go
Labels: approved

#141 [release-5.7] Backport PR grafana/loki#9405
  operator/CHANGELOG.md
  operator/apis/loki/v1/lokistack_types.go
  operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/community-openshift/manifests/loki.grafana.com_lokistacks.yaml
  operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/community/manifests/loki.grafana.com_lokistacks.yaml
  operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/openshift/manifests/loki.grafana.com_lokistacks.yaml
  operator/config/crd/bases/loki.grafana.com_lokistacks.yaml
  operator/docs/operator/api.md
  operator/internal/handlers/lokistack_create_or_update.go
  operator/internal/handlers/lokistack_create_or_update_test.go
  operator/internal/manifests/build_test.go
  operator/internal/manifests/config.go
  operator/internal/manifests/config_test.go
  operator/internal/manifests/gateway.go
  operator/internal/manifests/gateway_tenants.go
  operator/internal/manifests/gateway_tenants_test.go
  operator/internal/manifests/gateway_test.go
  operator/internal/manifests/internal/config/build_test.go
  operator/internal/manifests/internal/config/loki-config.yaml
  operator/internal/manifests/internal/config/options.go
  operator/internal/manifests/openshift/build_test.go
  operator/internal/manifests/openshift/options.go
  operator/internal/manifests/openshift/route.go
  operator/internal/manifests/openshift/var.go
  operator/internal/manifests/options.go
  operator/internal/manifests/options_test.go
  operator/internal/manifests/service_test.go
  operator/internal/manifests/var.go
Labels: lgtm, approved

#137 build: update loki and promtail Dockerfile base image to RHEL 9
  Dockerfile.ocp
  Dockerfile.promtail.ocp
Labels: approved

#138 backport: update loki and promtail Dockerfile base image to RHEL 9
  Dockerfile.ocp
  Dockerfile.promtail.ocp
Labels: lgtm, approved

#144 [release-5.7] Backport PR grafana/loki#9511
  operator/CHANGELOG.md
  operator/controllers/loki/lokistack_controller.go
Labels: lgtm, approved

#145 [release-5.6] Backport PR grafana/loki#9511
  operator/CHANGELOG.md
  operator/controllers/loki/lokistack_controller.go
Labels: lgtm, approved

#147 [release-5.7] Include runtime-config in compiling the SHA1 checksum
  operator/CHANGELOG.md
  operator/internal/manifests/config.go
Labels: lgtm, approved
