Repository openshift/loki, pull requests merged in 2023-10, with the labels that each got.

#190 [release-5.6] Backport PR grafana/loki#10562
  operator/CHANGELOG.md
  operator/apis/loki/v1/lokistack_types.go
  operator/apis/loki/v1/lokistack_webhook.go
  operator/apis/loki/v1/lokistack_webhook_test.go
  operator/apis/loki/v1/v1.go
  operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/manifests/loki.grafana.com_lokistacks.yaml
  operator/config/crd/bases/loki.grafana.com_lokistacks.yaml
  operator/config/manifests/bases/loki-operator.clusterserviceversion.yaml
  operator/docs/operator/api.md
  operator/internal/manifests/config.go
  operator/internal/manifests/config_test.go
  operator/internal/manifests/internal/config/build_test.go
  operator/internal/manifests/internal/config/loki-config.yaml
  operator/internal/manifests/internal/config/options.go
  operator/internal/manifests/memberlist.go
  operator/internal/manifests/var.go
Labels: lgtm, approved

#189 [release-5.7] Backport PR grafana/loki#10562
  operator/CHANGELOG.md
  operator/apis/loki/v1/lokistack_types.go
  operator/apis/loki/v1/v1.go
  operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/community-openshift/manifests/loki.grafana.com_lokistacks.yaml
  operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/community/manifests/loki.grafana.com_lokistacks.yaml
  operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/openshift/manifests/loki.grafana.com_lokistacks.yaml
  operator/config/crd/bases/loki.grafana.com_lokistacks.yaml
  operator/config/manifests/community-openshift/bases/loki-operator.clusterserviceversion.yaml
  operator/config/manifests/community/bases/loki-operator.clusterserviceversion.yaml
  operator/config/manifests/openshift/bases/loki-operator.clusterserviceversion.yaml
  operator/docs/operator/api.md
  operator/internal/manifests/config.go
  operator/internal/manifests/config_test.go
  operator/internal/manifests/internal/config/build_test.go
  operator/internal/manifests/internal/config/loki-config.yaml
  operator/internal/manifests/internal/config/options.go
  operator/internal/manifests/memberlist.go
  operator/internal/manifests/var.go
  operator/internal/validation/lokistack.go
  operator/internal/validation/lokistack_test.go
Labels: lgtm, approved

#191 Update from upstream repository
  operator/CHANGELOG.md
  operator/docs/lokistack/object_storage.md
  operator/internal/handlers/internal/storage/secrets.go
  operator/internal/handlers/internal/storage/secrets_test.go
  operator/internal/manifests/internal/config/loki-config.yaml
  operator/internal/manifests/storage/options.go
Labels: approved

#193 Update from upstream repository
  .github/workflows/operator-images.yaml
  .github/workflows/operator.yaml
  docs/sources/setup/install/helm/reference.md
  operator/.bingo/Variables.mk
  operator/.bingo/controller-gen.mod
  operator/.bingo/controller-gen.sum
  operator/.bingo/gofumpt.mod
  operator/.bingo/gofumpt.sum
  operator/.bingo/golangci-lint.mod
  operator/.bingo/golangci-lint.sum
  operator/.bingo/kind.mod
  operator/.bingo/kind.sum
  operator/.bingo/kustomize.sum
  operator/.bingo/operator-sdk.mod
  operator/.bingo/operator-sdk.sum
  operator/.bingo/promtool.mod
  operator/.bingo/promtool.sum
  operator/.bingo/variables.env
  operator/apis/config/v1/zz_generated.deepcopy.go
  operator/apis/loki/go.mod
  operator/apis/loki/go.sum
  operator/apis/loki/v1/zz_generated.deepcopy.go
  operator/apis/loki/v1beta1/zz_generated.deepcopy.go
  operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/community-openshift/manifests/loki.grafana.com_alertingrules.yaml
  operator/bundle/community-openshift/manifests/loki.grafana.com_lokistacks.yaml
  operator/bundle/community-openshift/manifests/loki.grafana.com_recordingrules.yaml
  operator/bundle/community-openshift/manifests/loki.grafana.com_rulerconfigs.yaml
  operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/community/manifests/loki.grafana.com_alertingrules.yaml
  operator/bundle/community/manifests/loki.grafana.com_lokistacks.yaml
  operator/bundle/community/manifests/loki.grafana.com_recordingrules.yaml
  operator/bundle/community/manifests/loki.grafana.com_rulerconfigs.yaml
  operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/openshift/manifests/loki.grafana.com_alertingrules.yaml
  operator/bundle/openshift/manifests/loki.grafana.com_lokistacks.yaml
  operator/bundle/openshift/manifests/loki.grafana.com_recordingrules.yaml
  operator/bundle/openshift/manifests/loki.grafana.com_rulerconfigs.yaml
  operator/config/crd/bases/loki.grafana.com_alertingrules.yaml
  operator/config/crd/bases/loki.grafana.com_lokistacks.yaml
  operator/config/crd/bases/loki.grafana.com_recordingrules.yaml
  operator/config/crd/bases/loki.grafana.com_rulerconfigs.yaml
  operator/config/rbac/role.yaml
  operator/config/webhook/manifests.yaml
  operator/go.mod
  operator/go.sum
  operator/internal/manifests/internal/config/build_test.go
  production/helm/loki/CHANGELOG.md
  production/helm/loki/Chart.yaml
  production/helm/loki/README.md
  production/helm/loki/templates/backend/statefulset-backend.yaml
  production/helm/loki/templates/single-binary/statefulset.yaml
  production/helm/loki/templates/write/statefulset-write.yaml
  production/helm/loki/values.yaml
Labels: approved

#195 [release-5.8] Backport PR grafana/loki#10854
  operator/CHANGELOG.md
  operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-retention.json
  operator/jsonnet/config.libsonnet
Labels: approved

#196 [release-5.8] Backport PR grafana/loki#10874
  operator/CHANGELOG.md
  operator/Dockerfile
  operator/Dockerfile.cross
  operator/go.mod
  operator/go.sum
Labels: approved

#197 [release-5.7] LOG-4640: Update golang.org/x/net and Go
  operator/CHANGELOG.md
  operator/Dockerfile
  operator/Dockerfile.cross
  operator/go.mod
  operator/go.sum
Labels: approved, jira/valid-reference

#198 [release-5.6] LOG-4639: Update golang.org/x/net and Go
  operator/.bingo/Variables.mk
  operator/.bingo/bingo.sum
  operator/.bingo/golangci-lint.mod
  operator/.bingo/golangci-lint.sum
  operator/.bingo/variables.env
  operator/CHANGELOG.md
  operator/Dockerfile
  operator/Dockerfile.cross
  operator/go.mod
  operator/go.sum
Labels: approved, jira/valid-reference

#199 [release-5.5] LOG-4638: Update golang.org/x/net and Go
  operator/.bingo/Variables.mk
  operator/.bingo/controller-gen.sum
  operator/.bingo/gofumpt.sum
  operator/.bingo/golangci-lint.mod
  operator/.bingo/golangci-lint.sum
  operator/.bingo/variables.env
  operator/CHANGELOG.md
  operator/Dockerfile
  operator/Dockerfile.cross
  operator/apis/config/v1/groupversion_info.go
  operator/apis/loki/v1/groupversion_info.go
  operator/go.mod
  operator/go.sum
  operator/internal/external/k8s/k8sfakes/fake_client_extensions.go
  operator/internal/manifests/openshift/rbac.go
  operator/internal/manifests/storage/schema.go
Labels: lgtm, approved, jira/valid-reference

#201 [release-5.8] Backport PR grafana/loki#10924
  operator/CHANGELOG.md
  operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
  operator/config/overlays/community-openshift/manager_related_image_patch.yaml
  operator/config/overlays/community/manager_related_image_patch.yaml
  operator/config/overlays/development/manager_related_image_patch.yaml
  operator/config/overlays/openshift/manager_related_image_patch.yaml
  operator/docs/operator/compatibility.md
  operator/hack/addons_dev.yaml
  operator/hack/addons_ocp.yaml
  operator/internal/manifests/var.go
  operator/jsonnet/jsonnetfile.json
  operator/jsonnet/jsonnetfile.lock.json
Labels: lgtm, approved

#202 [release-5.7] Backport PR grafana/loki#10924
  operator/CHANGELOG.md
  operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
  operator/config/overlays/community-openshift/manager_related_image_patch.yaml
  operator/config/overlays/community/manager_related_image_patch.yaml
  operator/config/overlays/development/manager_related_image_patch.yaml
  operator/config/overlays/openshift/manager_related_image_patch.yaml
  operator/docs/operator/compatibility.md
  operator/hack/addons_dev.yaml
  operator/hack/addons_ocp.yaml
  operator/internal/manifests/var.go
Labels: lgtm, approved

#203 [release-5.6] Backport PR grafana/loki#10924
  operator/CHANGELOG.md
  operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
  operator/config/overlays/development/manager_related_image_patch.yaml
  operator/config/overlays/openshift/manager_related_image_patch.yaml
  operator/config/overlays/production/manager_related_image_patch.yaml
  operator/docs/operator/compatibility.md
  operator/hack/addons_dev.yaml
  operator/hack/addons_ocp.yaml
  operator/internal/manifests/var.go
Labels: lgtm, approved
