Repository openshift/loki, pull requests merged in 2024-10, with the labels that each got.

#355 [release-6.0] Backport PR grafana/loki#14314
  operator/CHANGELOG.md
  operator/internal/status/components.go
  operator/internal/status/components_test.go
Labels: approved

#356 [release-5.9] Backport PR grafana/loki#14314
  operator/CHANGELOG.md
  operator/internal/status/components.go
  operator/internal/status/components_test.go
Labels: approved

#354 Update from upstream repository
  .github/workflows/helm-ci.yml
  .github/workflows/helm-release.yaml
  go.mod
  go.sum
  operator/internal/status/components.go
  operator/internal/status/components_test.go
  pkg/logql/engine.go
  pkg/logql/engine_test.go
  production/helm/loki/CHANGELOG.md
  production/helm/loki/Chart.yaml
  production/helm/loki/README.md
  tools/lambda-promtail/go.mod
  tools/lambda-promtail/go.sum
  vendor/modules.txt
Labels: approved

#357 [release-5.8] Backport PR grafana/loki#14314
  operator/CHANGELOG.md
  operator/internal/status/components.go
  operator/internal/status/components_test.go
Labels: approved

#359 [release-6.0] Backport PR grafana/loki#14331
  operator/CHANGELOG.md
  operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
  operator/config/overlays/community-openshift/manager_related_image_patch.yaml
  operator/config/overlays/community/manager_related_image_patch.yaml
  operator/config/overlays/development/manager_related_image_patch.yaml
  operator/config/overlays/openshift/manager_related_image_patch.yaml
  operator/docs/operator/compatibility.md
  operator/hack/addons_dev.yaml
  operator/hack/addons_ocp.yaml
  operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-reads.json
  operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-writes.json
  operator/internal/manifests/var.go
  operator/jsonnet/jsonnetfile.json
  operator/jsonnet/jsonnetfile.lock.json
Labels: approved

#361 [release-5.8] Backport PR grafana/loki#14331
  operator/CHANGELOG.md
  operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
  operator/config/overlays/community-openshift/manager_related_image_patch.yaml
  operator/config/overlays/community/manager_related_image_patch.yaml
  operator/config/overlays/development/manager_related_image_patch.yaml
  operator/config/overlays/openshift/manager_related_image_patch.yaml
  operator/docs/operator/compatibility.md
  operator/hack/addons_dev.yaml
  operator/hack/addons_ocp.yaml
  operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-reads.json
  operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-writes.json
  operator/internal/manifests/var.go
  operator/jsonnet/jsonnetfile.json
  operator/jsonnet/jsonnetfile.lock.json
Labels: lgtm, approved

#360 [release-5.9] Backport PR grafana/loki#14331
  operator/CHANGELOG.md
  operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
  operator/config/overlays/community-openshift/manager_related_image_patch.yaml
  operator/config/overlays/community/manager_related_image_patch.yaml
  operator/config/overlays/development/manager_related_image_patch.yaml
  operator/config/overlays/openshift/manager_related_image_patch.yaml
  operator/docs/operator/compatibility.md
  operator/hack/addons_dev.yaml
  operator/hack/addons_ocp.yaml
  operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-reads.json
  operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-writes.json
  operator/internal/manifests/var.go
  operator/jsonnet/jsonnetfile.json
  operator/jsonnet/jsonnetfile.lock.json
Labels: approved

#362 [release-5.6] Backport PR grafana/loki#14331
  operator/CHANGELOG.md
  operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
  operator/config/overlays/development/manager_related_image_patch.yaml
  operator/config/overlays/openshift/manager_related_image_patch.yaml
  operator/config/overlays/production/manager_related_image_patch.yaml
  operator/docs/operator/compatibility.md
  operator/hack/addons_dev.yaml
  operator/hack/addons_ocp.yaml
  operator/internal/manifests/var.go
Labels: lgtm, do-not-merge/hold, approved

#367 [release-5.6] Partial backport PR grafana/loki#14416
  .github/workflows/operator-bundle.yaml
  .github/workflows/operator-scorecard.yaml
  .github/workflows/operator.yaml
  operator/.bingo/Variables.mk
  operator/.bingo/bingo.mod
  operator/.bingo/bingo.sum
  operator/.bingo/controller-gen.mod
  operator/.bingo/controller-gen.sum
  operator/.bingo/gofumpt.mod
  operator/.bingo/gofumpt.sum
  operator/.bingo/golangci-lint.mod
  operator/.bingo/golangci-lint.sum
  operator/.bingo/kustomize.sum
  operator/.bingo/variables.env
  operator/.golangci.yaml
  operator/CHANGELOG.md
  operator/Dockerfile
  operator/Dockerfile.cross
  operator/apis/config/v1/zz_generated.deepcopy.go
  operator/apis/loki/v1/lokistack_webhook_test.go
  operator/apis/loki/v1/zz_generated.deepcopy.go
  operator/apis/loki/v1beta1/lokistack_types_test.go
  operator/apis/loki/v1beta1/zz_generated.deepcopy.go
  operator/bundle/manifests/loki.grafana.com_alertingrules.yaml
  operator/bundle/manifests/loki.grafana.com_lokistacks.yaml
  operator/bundle/manifests/loki.grafana.com_recordingrules.yaml
  operator/bundle/manifests/loki.grafana.com_rulerconfigs.yaml
  operator/cmd/loki-broker/main.go
  operator/config/crd/bases/loki.grafana.com_alertingrules.yaml
  operator/config/crd/bases/loki.grafana.com_lokistacks.yaml
  operator/config/crd/bases/loki.grafana.com_recordingrules.yaml
  operator/config/crd/bases/loki.grafana.com_rulerconfigs.yaml
  operator/config/rbac/role.yaml
  operator/config/webhook/manifests.yaml
  operator/controllers/loki/certrotation_controller_test.go
  operator/go.mod
  operator/go.sum
  operator/internal/certrotation/rotation_test.go
  operator/internal/handlers/internal/certificates/options_test.go
  operator/internal/handlers/internal/gateway/modes_test.go
  operator/internal/handlers/internal/gateway/tenant_secrets_test.go
  operator/internal/handlers/internal/rules/secrets_test.go
  operator/internal/handlers/internal/storage/ca_configmap_test.go
  operator/internal/handlers/internal/storage/secrets_test.go
  operator/internal/handlers/internal/tlsprofile/tlsprofile_test.go
  operator/internal/manifests/build_test.go
  operator/internal/manifests/config_test.go
  operator/internal/manifests/gateway_tenants_test.go
  operator/internal/manifests/gateway_test.go
  operator/internal/manifests/mutate_test.go
  operator/internal/manifests/service_monitor_test.go
  operator/internal/manifests/service_test.go
  operator/internal/manifests/storage/configure_test.go
  operator/internal/validation/alertingrule_test.go
  operator/internal/validation/openshift/alertingrule_test.go
  operator/internal/validation/openshift/recordingrule_test.go
  operator/internal/validation/recordingrule_test.go
Labels: approved

#365 [release-5.9] Partial backport PR grafana/loki#14416
  .github/workflows/operator-bundle.yaml
  .github/workflows/operator-scorecard.yaml
  .github/workflows/operator.yaml
  operator/.bingo/Variables.mk
  operator/.bingo/gofumpt.mod
  operator/.bingo/gofumpt.sum
  operator/.bingo/golangci-lint.mod
  operator/.bingo/golangci-lint.sum
  operator/.bingo/variables.env
  operator/.golangci.yaml
  operator/CHANGELOG.md
  operator/Dockerfile
  operator/Dockerfile.cross
  operator/apis/loki/v1beta1/alertingrule_types_test.go
  operator/apis/loki/v1beta1/lokistack_types_test.go
  operator/apis/loki/v1beta1/recordingrule_types_test.go
  operator/apis/loki/v1beta1/rulerconfig_types_test.go
  operator/cmd/loki-broker/main.go
  operator/controllers/loki/certrotation_controller_test.go
  operator/go.mod
  operator/go.sum
  operator/internal/certrotation/rotation_test.go
  operator/internal/handlers/internal/certificates/options_test.go
  operator/internal/handlers/internal/gateway/modes_test.go
  operator/internal/handlers/internal/gateway/tenant_secrets_test.go
  operator/internal/handlers/internal/rules/secrets_test.go
  operator/internal/handlers/internal/storage/ca_configmap_test.go
  operator/internal/handlers/internal/storage/secrets_test.go
  operator/internal/handlers/internal/storage/storage_test.go
  operator/internal/handlers/internal/tlsprofile/tlsprofile_test.go
  operator/internal/manifests/build_test.go
  operator/internal/manifests/config_test.go
  operator/internal/manifests/gateway_tenants_test.go
  operator/internal/manifests/gateway_test.go
  operator/internal/manifests/mutate_test.go
  operator/internal/manifests/node_placement_test.go
  operator/internal/manifests/openshift/alertingrule_test.go
  operator/internal/manifests/openshift/credentialsrequest_test.go
  operator/internal/manifests/openshift/recordingrule_test.go
  operator/internal/manifests/querier_test.go
  operator/internal/manifests/rules_config.go
  operator/internal/manifests/service_monitor_test.go
  operator/internal/manifests/service_test.go
  operator/internal/manifests/storage/configure_test.go
  operator/internal/metrics/lokistack_test.go
  operator/internal/status/components_test.go
  operator/internal/status/conditions_test.go
  operator/internal/status/lokistack_test.go
  operator/internal/validation/alertingrule_test.go
  operator/internal/validation/lokistack_test.go
  operator/internal/validation/openshift/alertingrule_test.go
  operator/internal/validation/openshift/recordingrule_test.go
  operator/internal/validation/recordingrule_test.go
  operator/internal/validation/rulerconfig_test.go
Labels: approved

#371 [release-6.0] Backport PR grafana/loki#14445
  operator/.bingo/Variables.mk
  operator/.bingo/kind.mod
  operator/.bingo/kind.sum
  operator/.bingo/operator-sdk.mod
  operator/.bingo/operator-sdk.sum
  operator/.bingo/variables.env
  operator/CHANGELOG.md
  operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
  operator/config/overlays/community/manager_auth_proxy_patch.yaml
Labels: approved

#374 [release-5.8] Backport PR grafana/loki#14526
  operator/CHANGELOG.md
  operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
  operator/config/overlays/community-openshift/manager_related_image_patch.yaml
  operator/config/overlays/community/manager_related_image_patch.yaml
  operator/config/overlays/development/manager_related_image_patch.yaml
  operator/config/overlays/openshift/manager_related_image_patch.yaml
  operator/docs/operator/compatibility.md
  operator/hack/addons_dev.yaml
  operator/hack/addons_ocp.yaml
  operator/internal/manifests/var.go
  operator/jsonnet/jsonnetfile.json
  operator/jsonnet/jsonnetfile.lock.json
Labels: approved

#370 LOG-6256: Disable automatic discovery of service name
  operator/internal/manifests/internal/config/build_test.go
  operator/internal/manifests/internal/config/loki-config.yaml
Labels: lgtm, approved, jira/valid-reference

#382 [release-6.0] Backport PR grafana/loki#14587
  operator/CHANGELOG.md
  operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-reads.json
  operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-writes.json
  operator/jsonnet/config.libsonnet
Labels: lgtm, approved

#379 [release-5.9] Backport PR grafana/loki#14445
  operator/.bingo/Variables.mk
  operator/.bingo/kind.mod
  operator/.bingo/kind.sum
  operator/.bingo/operator-sdk.mod
  operator/.bingo/operator-sdk.sum
  operator/.bingo/variables.env
  operator/CHANGELOG.md
  operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
  operator/config/overlays/community/manager_auth_proxy_patch.yaml
Labels: lgtm, approved

#380 [release-5.9] Backport PR grafana/loki#14526
  operator/CHANGELOG.md
  operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
  operator/config/overlays/community-openshift/manager_related_image_patch.yaml
  operator/config/overlays/community/manager_related_image_patch.yaml
  operator/config/overlays/development/manager_related_image_patch.yaml
  operator/config/overlays/openshift/manager_related_image_patch.yaml
  operator/docs/operator/compatibility.md
  operator/hack/addons_dev.yaml
  operator/hack/addons_ocp.yaml
  operator/internal/manifests/var.go
  operator/jsonnet/jsonnetfile.json
  operator/jsonnet/jsonnetfile.lock.json
Labels: lgtm, approved

#383 [release-5.8] Backport PR grafana/loki#14587
  operator/CHANGELOG.md
  operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-reads.json
  operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-writes.json
  operator/jsonnet/config.libsonnet
Labels: lgtm, approved

#384 [release-5.9] Backport PR grafana/loki#14587
  operator/CHANGELOG.md
  operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-reads.json
  operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-writes.json
  operator/jsonnet/config.libsonnet
Labels: approved

#385 Update from upstream repository
  docs/sources/release-notes/v3-1.md
  docs/sources/setup/install/helm/reference.md
  docs/sources/setup/upgrade/_index.md
  docs/sources/shared/configuration.md
  go.mod
  go.sum
  operator/api/loki/v1/lokistack_types.go
  operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/community-openshift/manifests/loki.grafana.com_lokistacks.yaml
  operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/community/manifests/loki.grafana.com_lokistacks.yaml
  operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
  operator/bundle/openshift/manifests/loki.grafana.com_lokistacks.yaml
  operator/config/crd/bases/loki.grafana.com_lokistacks.yaml
  operator/docs/operator/api.md
  operator/internal/manifests/internal/sizes.go
  pkg/storage/factory.go
  production/helm/loki/CHANGELOG.md
  production/helm/loki/templates/_helpers.tpl
  production/helm/loki/values.yaml
  vendor/github.com/twmb/franz-go/pkg/kfake/data.go
  vendor/modules.txt
Labels: lgtm, approved

#386 LOG-6295: Disable automatic discovery of service name
  operator/internal/manifests/internal/config/build_test.go
  operator/internal/manifests/internal/config/loki-config.yaml
Labels: lgtm, approved, jira/valid-reference

#387 LOG-6320: Disable log level discovery for OpenShift tenancy modes
  operator/CHANGELOG.md
  operator/internal/manifests/config.go
  operator/internal/manifests/internal/config/build_test.go
  operator/internal/manifests/internal/config/loki-config.yaml
  operator/internal/manifests/internal/config/options.go
Labels: lgtm, approved, jira/valid-reference

#388 LOG-6321: Disable log level discovery for OpenShift tenancy modes
  operator/CHANGELOG.md
  operator/internal/manifests/config.go
  operator/internal/manifests/internal/config/build_test.go
  operator/internal/manifests/internal/config/loki-config.yaml
  operator/internal/manifests/internal/config/options.go
Labels: lgtm, approved, jira/valid-reference

#389 LOG-6322: Disable log level discovery for OpenShift tenancy modes
  operator/CHANGELOG.md
  operator/internal/manifests/config.go
  operator/internal/manifests/internal/config/build_test.go
  operator/internal/manifests/internal/config/loki-config.yaml
  operator/internal/manifests/internal/config/options.go
Labels: lgtm, approved, jira/valid-reference
